table dim_sitc
	lineageTag: 84481956-d8f2-4946-a7ab-eaf1b64dcea6

	column section
		dataType: string
		isKey
		lineageTag: 8bee9aa0-8617-49f5-87c1-b47e53bc7542
		summarizeBy: none
		sourceColumn: section

	column desc_en
		dataType: string
		lineageTag: 870784f1-8206-4388-a395-86a9c57f2396
		summarizeBy: none
		sourceColumn: desc_en

	column desc_bm
		dataType: string
		lineageTag: be1383f4-9fd1-43a5-8242-804a21a026f2
		summarizeBy: none
		sourceColumn: desc_bm

	column section_label
		dataType: string
		lineageTag: 327c3c67-8090-4bda-845b-ca779ade10a3
		summarizeBy: none
		sourceColumn: section_label

	partition dim_sitc = m
		mode: import
		source =
				let
				    Source = Csv.Document(
				        File.Contents(ProcessedFolder & "\dim_sitc.csv"),
				        [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]
				    ),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Typed" = Table.TransformColumnTypes(#"Promoted Headers", {
				        {"section", type text},
				        {"desc_en", type text},
				        {"desc_bm", type text},
				        {"section_label", type text}
				    }, "en-US")
				in
				    #"Typed"

